stages:
  - build
  - test

build nodejs:
  stage: build
  image: node:latest
  script:
    - npm install
    - cd client
    - npm install

test nodejs:
  stage: test
  image: node:latest
  script: node ./tests/test.js