stages:
  - build
  - test
  - build_docker
  - deploy_kubernetes

build nodejs:
  stage: build
  image: node:latest
  script:
    - npm install

test nodejs:
  stage: test
  image: node:latest
  script: npm test

build docker image:
  stage: build_docker
  image: docker:latest
  services:
  - docker:dind
  script:
    - docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_TOKEN
    - docker build --rm -t $DOCKER_HUB_USER/gpvoluntariado:$CI_COMMIT_SHA -f deploy/Dockerfile .
    - docker push $DOCKER_HUB_USER/gpvoluntariado:$CI_COMMIT_SHA

deploy service:
  stage: deploy_kubernetes
  image: google/cloud-sdk:latest
  script:
    - echo $GKE_SERVICE_KEY | base64 -d > service-account.json
    - gcloud auth activate-service-account --key-file service-account.json --project=voluntariadoips-278217
    - gcloud config set project voluntariadoips-278217
    - gcloud config set compute/zone us-west1-b
    - gcloud container clusters get-credentials voluntariadoips-cluster
    - sed -i "s/%%imageTag%%/${CI_COMMIT_SHA}/" deploy/deployment.yml
    - sed -i "s/%%dockerUser%%/${DOCKER_HUB_USER}/" deploy/deployment.yml
    - kubectl apply -f deploy/namespace.yml
    - kubectl apply -f deploy/deployment.yml